--Level-2: Problem 1 - Store Wise Sales Summary 
--Scenario: 
--The regional manager wants to analyze total sales generated by each store. 
--📌 Requirements 
--1. Display store_name and total sales amount. 
--2. Calculate total sales using (quantity * list_price * (1 - discount)). 
--3. Include only completed orders (order_status = 4). 
--4. Group results by store_name. 
--5. Sort total sales in descending order.

-- store
create table stores (
    store_id int primary key,
    store_name varchar(50) not null
);
--data
insert into stores values
(1,'Pvallion store'),
(3,'pride store'),
(2,'city mall store');

--oredritem table
create table order_items (
    item_id int primary key,
    order_id int not null,
    product_id int not null,
    quantity int not null,
    list_price decimal(10,2) not null,
    discount decimal(4,2) default 0,
    constraint fk_orderitems_order
        foreign key (order_id) references orders(order_id),
    constraint fk_orderitems_product
        foreign key (product_id) references products(product_id)
);
--data
insert into order_items values
(1,101,1,2,800,0.10),
(2,102,2,1,650,0.05),
(3,103,4,1,1200,0.00);

--result querys
select
s.store_name,
sum(oi.quantity*oi.list_price*(1-oi.discount)) as total_sales
from stores s
inner join orders o
on s.store_id=o.store_id
inner join order_items oi
on o.order_id=oi.order_id
where o.order_status=4
group by s.store_name
order by total_sales desc;